CREATE TABLE screen (
	id INTEGER PRIMARY KEY,
	message TEXT
);

INSERT INTO screen (id, message)
VALUES (NULL, "THIS IS THE FIRST MESSAGE");

INSERT INTO screen (id, message)
VALUES (NULL, "THIS IS THE SECOND MESSAGE");